name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  country_picker: ^2.0.26
  dynamic_color: ^1.7.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.2.1+2
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
